---
title: "Organoid_IMC_Nils"
author: "Lasse Meyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Organoid IMC data analysis 

```{r}
# Load panel 
panel <- read.csv("/mnt/central_nas/tnbc_volume/TNBC_validation/Organoid_IMC_Nils/panel.csv")

panel$clean_target <- c("107Ag", "109Ag", "FSP1", "CK8_18", "CK5", "CD104", "MUC16", "STAT3", 
"H3", "YAP1", "Snail1", "CD14", "cMYC", "SOX4", "CD73", "CD117", 
"Neurofi", "CD274", "CD10", "CXCR4", "BCL2", "MUC1", "BAP1", 
"CD133", "CK7", "190Pt", "192Pt", "194Pt", "195Pt", "196Pt","198Pt")

# Load images 
images <- loadImages("/mnt/central_nas/tnbc_volume/TNBC_validation/Organoid_IMC_Nils/img/")

channelNames(images) <- panel$clean_target

# Load masks
masks <- loadImages("/mnt/central_nas/tnbc_volume/TNBC_validation/Organoid_IMC_Nils/masks/", as.is = TRUE)

# Subset to match 
images <- images[match(names(masks), names(images))]

# Set mcols and rename 
mcols(images) <- mcols(masks) <- DataFrame(sample_id = names(images))

names(masks) <- names(images) <- mcols(masks)$img_id <- mcols(images)$img_id <- paste0(str_split(names(images), "_", simplify = TRUE)[,4],"_",str_split(names(images), "_", simplify = TRUE)[,5])

# Visualize with cytoviewer
cytoviewer(image = images, mask = masks, img_id = "img_id")
```

```{r}
sce <- read_steinbock("/mnt/central_nas/tnbc_volume/TNBC_validation/Organoid_IMC_Nils/", regionprops_folder = NULL, graphs_folder = NULL, return_as = "sce")
sce
```

## Single-cell processing

We can set the `colnames` of the object to generate unique identifiers per cell:

```{r set-colnames}
colnames(sce) <- sce$cell_id <- paste0(sce$sample_id, "_", sce$ObjectNumber)

rowData(sce)$clean_target <- c("107Ag", "109Ag", "FSP1", "CK8_18", "CK5", "CD104", "MUC16", "STAT3", 
"H3", "YAP1", "Snail1", "CD14", "cMYC", "SOX4", "CD73", "CD117", 
"Neurofi", "CD274", "CD10", "CXCR4", "BCL2", "MUC1", "BAP1", 
"CD133", "CK7", "190Pt", "192Pt", "194Pt", "195Pt", "196Pt","198Pt")

sce$img_id <- paste0(str_split(sce$sample_id, "_", simplify = TRUE)[,4],"_",str_split(sce$sample_id, "_", simplify = TRUE)[,5])
  
rownames(sce) <- rowData(sce)$clean_target
```


Transform counts 

```{r}
#Transformed counts
assay(sce, "exprs") <- asinh(counts(sce)/1)
```

Add metadata 

```{r}
sce$organoid_line <- paste0(str_split(sce$sample_id, "_", simplify = TRUE)[,4])
```

Subset to B225 

```{r}
#sce <- sce[,sce$organoid_line == "BB225"]
```

## CK5/7 signature 

```{r}
## 5. CK5-7 signature
# 1. CK5
GMM_CK5 <- Mclust(assay(sce, "exprs")["CK5",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK5$classification == 2 & GMM_CK5$uncertainty == 0, 
                                        "CK5+",
                                        "CK5-"), 
                     KRT5_exprs = assay(sce, "exprs")["CK5",],
                     uncertainty = GMM_CK5$uncertainty)

#Visualize GMM
ggplot(GMM_df, aes(x = KRT5_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_CK5 <- GMM_df$class_epi

# 2. CK7
GMM_CK7 <- Mclust(assay(sce, "exprs")["CK7",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK7$classification == 2 & GMM_CK7$uncertainty == 0, 
                                        "CK7+",
                                        "CK7-"), 
                     KRT7_exprs = assay(sce, "exprs")["CK7",],
                     uncertainty = GMM_CK7$uncertainty)

#Visualize GMM
ggplot(GMM_df, aes(x = KRT7_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_CK7 <- GMM_df$class_epi

## Combine CK5/7 GMM scores 
sce$CK5_7_score <- ifelse(sce$GMM_tumor_CK5 == "CK5+" & sce$GMM_tumor_CK7 == "CK7+", "CK5/7+", 
       ifelse(sce$GMM_tumor_CK5 == "CK5+" & sce$GMM_tumor_CK7 == "CK7-", "CK5+",
              ifelse(sce$GMM_tumor_CK5 == "CK5-" & sce$GMM_tumor_CK7 == "CK7+", "CK7+","CK5/7-")))

## Visualize 
cur_dat <- t(assay(sce,"exprs")) %>% as.matrix %>% as.data.frame %>% dplyr::select("CK5","CK7")
cur_dat$CK5_7_score <- sce$CK5_7_score[match(rownames(cur_dat), sce$cell_id)]

library(wesanderson)
metadata(sce)$colors$CK5_7_score <- setNames(c("grey",wes_palette("Moonrise3")[1:3]), c("CK5/7-", "CK5/7+", "CK5+", "CK7+"))

ggplot(cur_dat, aes(x=CK7, y=CK5, color = CK5_7_score)) +
  geom_point(alpha = 0.5)+
  theme_classic()+
  xlab("CK7 exprs")+
  ylab("CK5 exprs")+
  scale_color_manual(values = metadata(sce)$colors$CK5_7_score)
```
```{r}
dittoBarPlot(sce, var = "CK5_7_score", group.by = "organoid_line")+
  scale_fill_manual(values = metadata(sce)$colors$CK5_7_score)
```
```{r}
# Define stem markers of interest
stem <- c("CD133","CD117")

#rowData(sce)$clean_target

cluster_mean_sce <- aggregateAcrossCells(sce, ids = sce$CK5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "exprs",
                                 subset.row = rowData(sce)$clean_target %in% stem)

scaled_mat <- t(scale(t(assay(cluster_mean_sce, "exprs"))))

anno <- colData(sce) %>% as.data.frame() %>% select(CK5_7_score) %>% group_by(CK5_7_score) %>% count()
anno <- anno[match(anno$CK5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(assay(cluster_mean_sce, "exprs"), col = viridis(100),name = "Mean Expression")
Heatmap(scaled_mat, name = "Scaled mean expression")

# Add row annotations 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$CK5_7_score))
```
```{r}
# Define keratin markers of interest
keratins <- c("CK5","CK7","CK8_18")

#rowData(sce)$clean_target

cluster_mean_sce <- aggregateAcrossCells(sce, ids = sce$CK5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "exprs",
                                 subset.row = rowData(sce)$clean_target %in% keratins)

scaled_mat <- t(scale(t(assay(cluster_mean_sce, "exprs"))))

anno <- colData(sce) %>% as.data.frame() %>% select(CK5_7_score) %>% group_by(CK5_7_score) %>% count()
anno <- anno[match(anno$CK5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(assay(cluster_mean_sce, "exprs"), col = viridis(100),name = "Mean Expression")
Heatmap(scaled_mat, name = "Scaled mean expression")

# Add row annotations 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$CK5_7_score))
```
```{r}
## Check results with cytoviewer 
cytoviewer(image = images, mask = masks, object = sce, img_id = "img_id", cell_id = "ObjectNumber")
```

