---
title: null
author: "Lasse Meyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# A stratification system for breast cancer based on basoluminal tumor cells and spatial tumor architecture, Meyer et al., 2025 

# Figure 5 and Figure S7/8

Data analysis scripts for re-creating Figure 5 and Figure S7/8. 

# Software requirements

```{r, message=FALSE,warning=FALSE}
library(SingleCellExperiment)
library(tidyverse)
library(ComplexHeatmap)
library(RColorBrewer)
library(conflicted)
library(ggpubr)
library(wesanderson)
library(scuttle)
library(viridis)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(scran)
library(patchwork)
library(gridExtra)
```

```{r, message=FALSE,warning=FALSE}
conflicts_prefer(dplyr::desc)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::count)
conflicts_prefer(dplyr::select)
```

# Read data

```{r}
# Available from Zenodo - DOI: 10.5281/zenodo.15396067
# File paths have to be adjusted by the user

## SCE objects
sce_mIF <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/SCE/sce_mIF.rds")
sce_PalWu <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/SCE/sce_PalWu.rds")
sce_PalWu_ALL <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/SCE/sce_PalWu_ALL.rds")
sce_organoid <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/SCE/sce_organoid.rds")

## Other
TCGA_DET <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_DET.rds")
TCGA_RES <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_RES.rds")
TCGA_NORMAL_DET <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_NORMAL_DET.rds")
TCGA_NORMAL_RES <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_NORMAL_RES.rds")
TCGA_COMBINED_DET <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_COMBINED_DET.rds")
TCGA_COMBINED_RES <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/TCGA_COMBINED_RES.rds")
MDACC_ES <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/MDACC_ES.rds")
MDACC_EXP <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/MDACC_EXP.rds")
GeneSignatures <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/00_final_files/OTHER/GeneSignatures.rds") 
```

# Figure 5

## 5A

```{r}
# Define stem markers of interest
stem <- c("SOX9","KIT","PROM1","YAP1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","BRCA2", "TGFB2", "ANXA8","MUC1", "CD24", "TNFAIP3", "ERBB3", "TNFRSF11A")

stem_rel <- stem[stem %in% rownames(assay(TCGA_DET))]

## Create heatmap body 
df <- t(assay(TCGA_DET)[stem_rel,]) %>% as.data.frame 
df <- df %>% rownames_to_column("PID")
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(df$PID, colnames(TCGA_DET))]
mat <- df %>% pivot_longer(cols = 2:(ncol(df)-1), names_to = "gene", values_to = "exprs") %>% group_by(KRT5_7_score, gene) %>% summarize(mean = mean(exprs))
ht <- mat %>% pivot_wider(names_from = "gene", values_from = "mean") %>% column_to_rownames("KRT5_7_score")

## Create row annotation 
anno <- df %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% count()
anno <- anno[match(anno$KRT5_7_score, rownames(ht)),]

## Print heatmap 
Heatmap(scale(ht), name = "Scaled mean Z-scores")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## 5B 

```{r}
# Define stem markers of interest
stem <- c("SOX9","KIT","PROM1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","MUC1","EZH2", "YAP1","ANXA8", "TGFB2", "CD24", "TNFAIP3", "ERBB3", "TNFRSF11A")
stem_rel <- stem[stem %in% rownames(MDACC_EXP)]

## Create heatmap body 
df <- t(MDACC_EXP[stem_rel,]) %>% as.data.frame 
df <- df %>% rownames_to_column("PID")
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(df$PID, colnames(MDACC_ES))]
mat <- df %>% pivot_longer(cols = 2:(ncol(df)-1), names_to = "gene", values_to = "exprs") %>% group_by(KRT5_7_score, gene) %>% dplyr::summarize(mean = mean(exprs))
ht <- mat %>% pivot_wider(names_from = "gene", values_from = "mean") %>% column_to_rownames("KRT5_7_score")

## Create row annotation 
anno <- df %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% dplyr::count()
anno <- anno[match(anno$KRT5_7_score, rownames(ht)),]

## Print heatmap 
Heatmap(scale(ht), name = "Scaled mean Z-scores")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## 5C

```{r}
## Luminal progenitor signatures (Lim et al.)
lum_progenitor_sig_up <- GeneSignatures$LuPro_Lim
lum_progenitor_sig_up_rel <- lum_progenitor_sig_up[lum_progenitor_sig_up %in% rownames(assay(TCGA_DET))]

df <- t(assay(TCGA_DET)[lum_progenitor_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Luminal progenitor signature")+
  stat_compare_means()
```

## 5D

```{r}
## Luminal progenitor signatures (Lim et al.)
lum_progenitor_sig_up <- GeneSignatures$LuPro_Lim
lum_progenitor_sig_up_rel <- lum_progenitor_sig_up[lum_progenitor_sig_up %in% rownames(MDACC_EXP)]

df <- t(MDACC_EXP[lum_progenitor_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(rownames(df), colnames(MDACC_ES))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

col_score <- setNames(c("grey",wes_palette("Moonrise3")[1:3]), c("KRT5/7-", "KRT5/7+","KRT5+", "KRT7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = col_score)+
  theme_classic()+
  ylab("Luminal progenitor signature")+
  stat_compare_means()
```

## 5E

```{r}
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(TCGA_DET))]

df <- t(assay(TCGA_DET)[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()
```

## 5F

```{r}
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(MDACC_EXP)]

df <- t(MDACC_EXP[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(rownames(df), colnames(MDACC_ES))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

col_score <- setNames(c("grey",wes_palette("Moonrise3")[1:3]), c("KRT5/7-", "KRT5/7+","KRT5+", "KRT7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = col_score)+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()
```

## 5I

```{r}
sce_mIF_sub <- sce_mIF[,sce_mIF$Image %in% c("pyr_final_B08_42871_7_1", "pyr_final_B10_21451_30_2", "pyr_final_B08_33039_7_3", "pyr_final_B16_74059_16_2")]

# Stem markers
cluster_mean_sce_mIF <- aggregateAcrossCells(sce_mIF_sub, ids = sce_mIF_sub$CK5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "min_max",
                                 subset.row = rowData(sce_mIF_sub)$stem_channel)

Heatmap(scale(t(assay(cluster_mean_sce_mIF, "min_max"))), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(cluster_mean_sce_mIF$ncells, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(cluster_mean_sce_mIF$CK5_7_score))
```

## 5K

```{r}
# SOX9 nuclear vs cytoplasmic
sce_mIF_SOX9 <- sce_mIF[,sce_mIF$SOX9_manual == "SOX9+"]

rowData(sce_mIF_SOX9)$SOX9_channel <- rownames(sce_mIF) %in% c("SOX9_nuc", "SOX9_cyto")

sce_mIF_SOX9_sub <- sce_mIF_SOX9[,sce_mIF_SOX9$Image %in% c("pyr_final_B08_42871_7_1", "pyr_final_B10_21451_30_2", "pyr_final_B08_33039_7_3", "pyr_final_B16_74059_16_2")]

cluster_mean_sce_mIF_SOX9 <- aggregateAcrossCells(sce_mIF_SOX9_sub, ids = sce_mIF_SOX9_sub$CK5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "min_max",
                                 subset.row = rowData(sce_mIF_SOX9_sub)$SOX9_channel)

Heatmap(scale(t(assay(cluster_mean_sce_mIF_SOX9, "min_max"))), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(cluster_mean_sce_mIF_SOX9$ncells, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(cluster_mean_sce_mIF_SOX9$CK5_7_score))
```

# Figure S7

## S7A

```{r}
# NOTE: Due to random ranking of genes with identical significance, this plot can vary slighty. 
TCGA_RES <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/TCGA_BRCA_DESeq_VST_full_CombinedScore.rds")

organism <- "org.Hs.eg.db"

# Prepare input gene list based on log2foldchanges 
original_gene_list <- TCGA_RES$log2FoldChange
names(original_gene_list) <- rownames(TCGA_RES)
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = TRUE) # sort in decreasing order

# Run GO analysis
gse <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             minGSSize = 50, 
             maxGSSize = 1000, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "BH")

# Visualization
emapplot(pairwise_termsim(gse), showCategory = 15, color = "enrichmentScore", layout = "circle")
```

## S7B/C

```{r}
# NOTE: Due to random ranking of genes with identical significance, this plot can vary slighty. 
entrez.ids <- mapIds(org.Hs.eg.db, keys=rownames(TCGA_RES), column="ENTREZID", keytype="SYMBOL")
entrez.ids <- entrez.ids[!duplicated(entrez.ids)]

df <- data.frame(log_change = gene_list, 
           SYMBOL = names(gene_list))
df$ENTREZ <- entrez.ids[match(df$SYMBOL, names(entrez.ids))]
df <- df[!is.na(df$ENTREZ),]
gene_list_kegg <- df$log_change
names(gene_list_kegg) <- df$ENTREZ

# Run KEGG
gseKEGG <- gseKEGG(geneList=gene_list_kegg, 
        organism = "hsa",
        keyType = "kegg", 
        minGSSize = 50, 
        maxGSSize = 500, 
        pvalueCutoff = 0.05, 
        verbose = TRUE, 
        pAdjustMethod = "BH")

# Visualization 
## EMAP plot 
emapplot(pairwise_termsim(gseKEGG), showCategory = 15,color = "enrichmentScore", layout = "circle")

## GSEA plot
gseaplot2(gseKEGG, title = gseKEGG$Description[gseKEGG$Description == "TNF signaling pathway"], geneSetID = 1)
gseaplot2(gseKEGG, title = gseKEGG$Description[gseKEGG$Description == "NF-kappa B signaling pathway"], geneSetID = 1)
```

## S7D

```{r}
# TCGA
## Pan-Alveolar signature (Gray et al.)
panAV_sig_up <- GeneSignatures$panAV_Gray
panAV_sig_up_rel <- panAV_sig_up[panAV_sig_up %in% rownames(assay(TCGA_DET))]

df <- t(assay(TCGA_DET)[panAV_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Pan-Alveolar signature")+
  stat_compare_means()
```
```{r}
# MDACC 
## Pan-Alveolar signature (Gray et al.)
panAV_sig_up <- GeneSignatures$panAV_Gray
panAV_sig_up_rel <- panAV_sig_up[panAV_sig_up %in% rownames(MDACC_EXP)]

df <- t(MDACC_EXP[panAV_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(rownames(df), colnames(MDACC_ES))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = col_score)+
  theme_classic()+
  ylab("Pan-Alveolar signature")+
  stat_compare_means()
```

## S7E

```{r}
# TCGA - TNBC
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(TCGA_DET))]

TNBC_PID <- colnames(TCGA_DET[,TCGA_DET$TNBC == "TNBC"])
TCGA_DET_TNBC <- TCGA_DET[, colnames(TCGA_DET) %in% TNBC_PID]
df <- t(assay(TCGA_DET_TNBC)[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()+
  geom_signif(
    comparisons = list(c("KRT5/7+", "KRT5+"), c("KRT5/7+", "KRT5/7-"),c("KRT5/7+", "KRT7+")),
    map_signif_level = FALSE, step_increase = 0.1, test = "t.test"
  )
```

```{r}
# MDACC - TNBC
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(MDACC_EXP)]

TNBC_PID <- colnames(MDACC_ES[,MDACC_ES$TNBC_assign_lehmann == "TNBC"])
MDACC_EXP_TNBC <- MDACC_EXP[, colnames(MDACC_EXP) %in% TNBC_PID]
df <- t(MDACC_EXP_TNBC[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(rownames(df), colnames(MDACC_ES))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = col_score)+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()+
  geom_signif(
    comparisons = list(c("KRT5/7+", "KRT5+"), c("KRT5/7+", "KRT5/7-"),c("KRT5/7+", "KRT7+")),
    map_signif_level = FALSE, step_increase = 0.1, test = "t.test"
  )
```

## S7F

```{r}
# NOTE: Due to random ranking of genes with identical significance, this plot can vary slighty. 
sce_PalWu_ALL$KRT5_7_score_sum <- ifelse(sce_PalWu_ALL$KRT5_7_score == "KRT5/7+", "KRT5/7+", "Not_KRT5/7+")
sce_PalWu_ALL$KRT5_7_score_sum <- factor(sce_PalWu_ALL$KRT5_7_score_sum, levels = c("Not_KRT5/7+","KRT5/7+"))
summed <- aggregateAcrossCells(sce_PalWu_ALL, id=colData(sce_PalWu_ALL)[,c("KRT5_7_score_sum", "PID")])

# Pseudobulk-profile DGE
res <- pseudoBulkDGE(summed,
    label=rep("dummy", ncol(summed)),
    design=~factor(PID) + KRT5_7_score_sum,
    coef="KRT5_7_score_sumKRT5/7+")[[1]]

organism <- "org.Hs.eg.db"

# Prepare input gene list based on log2foldchanges 
original_gene_list <- res$logFC
names(original_gene_list) <- rownames(res)
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = TRUE)

# Run GO analysis
set.seed(22)
gse <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             minGSSize = 50, 
             maxGSSize = 1000, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "BH")

# Visualization
emapplot(pairwise_termsim(gse), showCategory = 10, color = "enrichmentScore", layout = "circle")
```

## S7G

```{r}
stem <- c("SOX9","KIT","PROM1","YAP1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","BRCA2", "TGFB2", "MUC1","ANXA8", "CD24", "TNFAIP3", "ERBB3", "TNFRSF11A")

stem_rel <- stem[stem %in% rownames(sce_PalWu_ALL)]

cluster_mean_sce_all <- aggregateAcrossCells(sce_PalWu_ALL, ids = sce_PalWu_ALL$KRT5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rownames(sce_PalWu_ALL) %in% stem_rel)

scaled_mat <- t(scale(t(assay(cluster_mean_sce_all, "logcounts"))))

anno <- colData(sce_PalWu_ALL) %>% as.data.frame() %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% dplyr::count()
anno <- anno[match(anno$KRT5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## S7H

```{r}
## Luminal progenitor signature (Lim et al.)
lum_progenitor_sig_up <- GeneSignatures$LuPro_Lim
lum_progenitor_sig_up_rel <- lum_progenitor_sig_up[lum_progenitor_sig_up %in% rownames(assay(sce_PalWu_ALL))]

stem_mean_sce_PalWu_ALL <- assay(sce_PalWu_ALL, "logcounts")[rownames(sce_PalWu_ALL) %in% lum_progenitor_sig_up_rel,]
stem_mean_sce_PalWu_ALL <- as.data.frame(as.matrix(stem_mean_sce_PalWu_ALL))
test <- as.data.frame(scale(t(stem_mean_sce_PalWu_ALL)), center = TRUE)
test$KRT5_7_score <- sce_PalWu_ALL$KRT5_7_score[match(rownames(test), colnames(sce_PalWu_ALL))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)]), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Luminal progenitor signature")


## Pan-Alveolar signature (Gray et al.)
panAV_sig_up <- GeneSignatures$panAV_Gray
panAV_sig_up_rel <- panAV_sig_up[panAV_sig_up %in% rownames(assay(sce_PalWu_ALL))]

stem_mean_sce_PalWu_ALL <- assay(sce_PalWu_ALL, "logcounts")[rownames(sce_PalWu_ALL) %in% panAV_sig_up_rel,]
stem_mean_sce_PalWu_ALL <- as.data.frame(as.matrix(stem_mean_sce_PalWu_ALL))
test <- as.data.frame(scale(t(stem_mean_sce_PalWu_ALL)), center = TRUE)
test$KRT5_7_score <- sce_PalWu_ALL$KRT5_7_score[match(rownames(test), colnames(sce_PalWu_ALL))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)]), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Pan-Alveolar signature")


## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(sce_PalWu_ALL))]

stem_mean_sce_PalWu_ALL <- assay(sce_PalWu_ALL, "logcounts")[rownames(sce_PalWu_ALL) %in% BL_sig_up_rel,]
stem_mean_sce_PalWu_ALL <- as.data.frame(as.matrix(stem_mean_sce_PalWu_ALL))
test <- as.data.frame(scale(t(stem_mean_sce_PalWu_ALL)), center = TRUE)
test$KRT5_7_score <- sce_PalWu_ALL$KRT5_7_score[match(rownames(test), colnames(sce_PalWu_ALL))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)]), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Basoluminal signature")
```

## S7I

```{r}
stem <- c("SOX9","KIT","PROM1","YAP1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","BRCA2", "TGFB2", "ANXA8","MUC1", "CD24", "TNFAIP3", "ERBB3", "TNFRSF11A")

stem_rel <- stem[stem %in% rowData(sce_organoid)$Symbol]

cluster_mean_sce <- aggregateAcrossCells(sce_organoid, ids = sce_organoid$KRT5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce_organoid)$Symbol %in% stem_rel)

scaled_mat <- t(scale(t(assay(cluster_mean_sce, "logcounts"))))

anno <- colData(sce_organoid) %>% as.data.frame() %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% dplyr::count()
anno <- anno[match(anno$KRT5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```


## S7J

```{r}
## Luminal progenitor signature (Lim et al.)
lum_progenitor_sig_up <- GeneSignatures$LuPro_Lim
lum_progenitor_sig_up_rel <- lum_progenitor_sig_up[lum_progenitor_sig_up %in% rownames(assay(sce_organoid))]

stem_mean_sce_organoid <- assay(sce_organoid, "logcounts")[rowData(sce_organoid)$Symbol %in% lum_progenitor_sig_up_rel,]
stem_mean_sce_organoid <- as.data.frame(as.matrix(stem_mean_sce_organoid))
test <- as.data.frame(scale(t(stem_mean_sce_organoid)), center = TRUE)
test$KRT5_7_score <- sce_organoid$KRT5_7_score[match(rownames(test), colnames(sce_organoid))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)], na.rm = TRUE), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Luminal progenitor signature")


## Pan-Alveolar signature (Gray et al.)
panAV_sig_up <- GeneSignatures$panAV_Gray
panAV_sig_up_rel <- panAV_sig_up[panAV_sig_up %in% rownames(assay(sce_organoid))]

stem_mean_sce_organoid <- assay(sce_organoid, "logcounts")[rownames(sce_organoid) %in% panAV_sig_up_rel,]
stem_mean_sce_organoid <- as.data.frame(as.matrix(stem_mean_sce_organoid))
test <- as.data.frame(scale(t(stem_mean_sce_organoid)), center = TRUE)
test$KRT5_7_score <- sce_organoid$KRT5_7_score[match(rownames(test), colnames(sce_organoid))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)], na.rm = TRUE), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Pan-Alveolar signature")


## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(sce_organoid))]

stem_mean_sce_organoid <- assay(sce_organoid, "logcounts")[rownames(sce_organoid) %in% BL_sig_up_rel,]
stem_mean_sce_organoid <- as.data.frame(as.matrix(stem_mean_sce_organoid))
test <- as.data.frame(scale(t(stem_mean_sce_organoid)), center = TRUE)
test$KRT5_7_score <- sce_organoid$KRT5_7_score[match(rownames(test), colnames(sce_organoid))]
plot_df <- data.frame(signature_score = rowSums(test[1:(ncol(test)-1)], na.rm = TRUE), cat = test$KRT5_7_score)
plot_df$cat <- factor(plot_df$cat, levels = c("KRT5/7-", "KRT7+", "KRT5+","KRT5/7+"))

# Heatmap
heat <- plot_df %>% group_by(cat) %>% summarise(mean = mean(signature_score)) %>% pivot_wider(names_from = cat, values_from = mean)
Heatmap(heat, name = "Basoluminal signature")
```

# Figure S8

## S8A

```{r}
plot <- as.data.frame(t(counts(TCGA_NORMAL_RES, normalized = TRUE)[rownames(counts(TCGA_NORMAL_RES, normalized = TRUE)) %in% c("KRT5","KRT7"),]))
plot$KRT5_7_score <- TCGA_NORMAL_DET$KRT5_7_score[match(rownames(plot),colnames(TCGA_NORMAL_DET))]
plot$GMM_KRT5 <- TCGA_NORMAL_DET$GMM_KRT5[match(rownames(plot),colnames(TCGA_NORMAL_DET))]
plot$GMM_KRT7 <- TCGA_NORMAL_DET$GMM_KRT7[match(rownames(plot),colnames(TCGA_NORMAL_DET))]

main <- ggplot(plot, aes(x=KRT7, y=KRT5, color = KRT5_7_score)) +
  geom_point(size = 2, alpha = 0.5)+
  theme_classic()+
  xlab("CK7 normalized counts")+
  ylab("CK5 normalized counts")+
  coord_cartesian()+
  scale_color_manual(values = metadata(TCGA_NORMAL_DET)$colors$KRT57_score)+
  guides(color = "none")

y_side <- ggplot(plot, aes(x = KRT5, fill=GMM_KRT5)) + 
  geom_density(alpha=0.8) + 
  scale_fill_manual(values = c('#999999','#F4B5BD')) + 
  theme_classic()+
  theme(legend.position = "none", axis.title.y = element_blank())+
  coord_flip()

x_side <- ggplot(plot, aes(x = KRT7, fill=GMM_KRT7)) + 
  geom_density(alpha=0.8) + 
  scale_fill_manual(values = c('#999999','#9C964A')) + 
  coord_cartesian()+
  theme_classic()+
  theme(legend.position = "none", axis.title.x = element_blank())

blankPlot <- ggplot()+geom_blank(aes(1,1)) + 
  cowplot::theme_nothing()

grid.arrange(x_side, blankPlot, main, y_side, 
        ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))
```

## S8B

```{r}
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(TCGA_NORMAL_DET))]

df <- t(assay(TCGA_NORMAL_DET)[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_NORMAL_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_NORMAL_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_NORMAL_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()
```

## S8C

```{r}
# Define keratins of interest
keratins <- c("KRT5","KRT7","KRT15","KRT8","KRT18","KRT19", "KRT14","KRT17","ITGA6","EPCAM")

## Create heatmap body 
df <- t(assay(TCGA_NORMAL_DET)[keratins,]) %>% as.data.frame 
df <- df %>% rownames_to_column("PID")
df$KRT5_7_score <- TCGA_NORMAL_DET$KRT5_7_score[match(df$PID, colnames(TCGA_NORMAL_DET))]
mat <- df %>% pivot_longer(cols = 2:(ncol(df)-1), names_to = "gene", values_to = "exprs") %>% group_by(KRT5_7_score, gene) %>% summarize(mean = mean(exprs))
ht <- mat %>% pivot_wider(names_from = "gene", values_from = "mean") %>% column_to_rownames("KRT5_7_score")

## Create row annotation 
anno <- df %>% dplyr::select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% count()
anno <- anno[match(anno$KRT5_7_score, rownames(ht)),]

## Print heatmap 
Heatmap(scale(ht), name = "Scaled mean Z-scores")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## S8D

```{r}
# Define stem markers of interest
stem <- c("SOX9","KIT","PROM1","YAP1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","BRCA2", "TGFB2", "ANXA8","MUC1", "CD24", "TNFAIP3", "ERBB3", "TNFRSF11A")
stem_rel <- stem[stem %in% rownames(assay(TCGA_NORMAL_DET))]

## Create heatmap body 
df <- t(assay(TCGA_NORMAL_DET)[stem_rel,]) %>% as.data.frame 
df <- df %>% rownames_to_column("PID")
df$KRT5_7_score <- TCGA_NORMAL_DET$KRT5_7_score[match(df$PID, colnames(TCGA_NORMAL_DET))]
mat <- df %>% pivot_longer(cols = 2:(ncol(df)-1), names_to = "gene", values_to = "exprs") %>% group_by(KRT5_7_score, gene) %>% summarize(mean = mean(exprs))
ht <- mat %>% pivot_wider(names_from = "gene", values_from = "mean") %>% column_to_rownames("KRT5_7_score")

## Create row annotation 
anno <- df %>% dplyr::select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% count()
anno <- anno[match(anno$KRT5_7_score, rownames(ht)),]

## Print heatmap 
Heatmap(scale(ht), name = "Scaled mean Z-scores")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## S8E

```{r}
## Basoluminal signature (Gray et al.)
BL_sig_up <- GeneSignatures$BL_Gray
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(TCGA_COMBINED_DET))]

df <- t(assay(TCGA_COMBINED_DET)[BL_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_COMBINED_DET$KRT5_7_score_anno[match(rownames(df), colnames(TCGA_COMBINED_DET))]

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_brewer(palette = "Set1")+
  theme_classic()+
  ylab("Basoluminal signature")+
  stat_compare_means()
```

## S8F

```{r}
# NOTE: Due to random ranking of genes with identical significance, this plot can vary slighty. 
organism <- "org.Hs.eg.db"

# Prepare input gene list based on log2foldchanges 
original_gene_list <- TCGA_COMBINED_RES$log2FoldChange
names(original_gene_list) <- rownames(TCGA_COMBINED_RES)
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = TRUE)

# Run GO analysis
gse <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             minGSSize = 50, 
             maxGSSize = 1000, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "BH")

# Visualization
emapplot(pairwise_termsim(gse), showCategory = 10, color = "enrichmentScore", layout = "circle")
```

## S8G

```{r}
## Chromosomal instability signature (Carter et al.)
chrom_sig_up <- GeneSignatures$ChromInst_Carter
chrom_sig_up_rel <- chrom_sig_up[chrom_sig_up %in% rownames(assay(TCGA_COMBINED_DET))]

df <- t(assay(TCGA_COMBINED_DET)[chrom_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_COMBINED_DET$KRT5_7_score_anno[match(rownames(df), colnames(TCGA_COMBINED_DET))]

ggplot(df, aes(x = reorder(KRT5_7_score,signature_sum, FUN = median), y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_brewer(palette = "Set1")+
  theme_classic()+
  ylab("Chromosomal instability signature")+
  stat_compare_means()
```

## S8H

```{r}
## Chromosomal instability signature (Carter et al.)
chrom_sig_up <- GeneSignatures$ChromInst_Carter
chrom_sig_up_rel <- chrom_sig_up[chrom_sig_up %in% rownames(assay(TCGA_DET))]

df <- t(assay(TCGA_DET)[chrom_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- TCGA_DET$KRT5_7_score[match(rownames(df), colnames(TCGA_DET))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = reorder(KRT5_7_score, signature_sum, FUN = median), y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(TCGA_DET)$colors$KRT57_score)+
  theme_classic()+
  ylab("Chromosomal instability signature")+
  stat_compare_means()
```

## S8I

```{r}
## Chromosomal instability signature (Carter et al.)
chrom_sig_up <- GeneSignatures$ChromInst_Carter
chrom_sig_up_rel <- chrom_sig_up[chrom_sig_up %in% rownames(MDACC_EXP)]

df <- t(MDACC_EXP[chrom_sig_up_rel ,]) %>% as.data.frame
df <- as.data.frame(scale(df))
df$signature_sum <- rowSums(df,na.rm = TRUE)
df$KRT5_7_score <- MDACC_ES$KRT5_7_score[match(rownames(df), colnames(MDACC_ES))]
df$KRT5_7_score <- factor(df$KRT5_7_score, levels = c("KRT5/7-", "KRT7+", "KRT5+", "KRT5/7+"))

ggplot(df, aes(x = KRT5_7_score, y = signature_sum))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = KRT5_7_score), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = col_score)+
  theme_classic()+
  ylab("Chromosomal instability signature")+
  stat_compare_means()
```

## S8L 

```{r}
sce_mIF_sub <- sce_mIF[,sce_mIF$Image %in% c("pyr_final_B08_42871_7_1", "pyr_final_B10_21451_30_2", "pyr_final_B08_33039_7_3", "pyr_final_B16_74059_16_2")]

# Keratin markers
cluster_mean_sce_mIF <- aggregateAcrossCells(sce_mIF_sub, ids = sce_mIF_sub$CK5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "min_max",
                                 subset.row = rowData(sce_mIF_sub)$keratin_channel)

Heatmap(scale(t(assay(cluster_mean_sce_mIF, "min_max"))), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(cluster_mean_sce_mIF$ncells, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(cluster_mean_sce_mIF$CK5_7_score))
```

# Session Info 

```{r}
sessionInfo()
```