---
title: "SCRNAseq_organoid_analysis"
author: "Lasse Meyer"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Software requirements

```{r lib, message=FALSE,warning=FALSE}
#Data containers
library(SpatialExperiment)
library(SingleCellExperiment)

#Data processing
library(scuttle)
library(scater)
library(scran)
library(imcRtools)

#Data visualization
library(cytomapper)
library(dittoSeq)
library(pheatmap)
library(cowplot)
library(ComplexHeatmap)
library(circlize)

#Utilities
library(tidyverse)
library(openxlsx)
library(stringr)
library(patchwork)
library(parallel)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(tiff)
library(ggrepel)
library(EBImage)
library(viridis)
library(mclust)
library(Rphenograph)
library(igraph)
library(RColorBrewer)
library(foreach)
library(clValid)
library(bluster)
library(psych)
library(corrplot)
library(psych)

#Batch correction
library(batchelor)
```

# scRNAseq dataset from Haithem

## Load data 

```{r}
sce <- readRDS("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/03_data/sce_scRNA_organoid_final.rds")
sce
```

## Subset to tumor cells 

```{r}
# Select epithelial cells
sce <- sce[,!sce$celltypes %in% c("endothelial", "B_cell", "T_cell","macrophage","fibroblast")]

# Select tumor samples
sce <- sce[,str_detect(sce$Patient_ID, "T")]
```

## Explore dataset 

```{r}
# UMAP 
plotUMAP(sce, colour_by="celltypes")
plotUMAP(sce, colour_by="Patient_ID")

#Visualize genes of interest
keratins <- c("KRT5", "KRT7", "KRT8", "KRT14","KRT18","KRT19", "KRT15","ITGA6","EPCAM")
all_plots_UMAP <- lapply(keratins,
                    function(x){
                      p <- plotReducedDim(sce, dimred = "UMAP", colour_by = x, by_exprs_values = "logcounts", point_size = 0.3)
                      return(p)                    
                    })

library(cowplot)
all_plots_UMAP_keratins <- plot_grid(plotlist = all_plots_UMAP)
all_plots_UMAP_keratins
```

Observation: Strong overlap of CK7 and CK5 in the "basal" compartment 

## CK5/7 Signature 

```{r}
## add CK5 and CK7 GMM
# 1. CK5
GMM_CK5 <- Mclust(assay(sce, "logcounts")["KRT5",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK5$classification == 2, #& GMM_CK5$uncertainty < 0.01, 
                                        "KRT5+",
                                        "KRT5-"), 
                     KRT5_exprs = assay(sce, "logcounts")["KRT5",],
                     uncertainty = GMM_CK5$uncertainty)

#Visualize GMM
ggplot(GMM_df, aes(x = KRT5_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_KRT5 <- GMM_df$class_epi

# 2. CK7
GMM_CK7 <- Mclust(assay(sce, "logcounts")["KRT7",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK7$classification == 2, #& GMM_CK7$uncertainty < 0.01,
                                        "KRT7+",
                                        "KRT7-"), 
                     KRT7_exprs = assay(sce, "logcounts")["KRT7",],
                     uncertainty = GMM_CK7$uncertainty)


#Visualize GMM
ggplot(GMM_df, aes(x = KRT7_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_KRT7 <- GMM_df$class_epi

## Combine KRT5/7 GMM scores 
sce$KRT5_7_score <- ifelse(sce$GMM_tumor_KRT5 == "KRT5+" & sce$GMM_tumor_KRT7 == "KRT7+", "KRT5/7+", 
       ifelse(sce$GMM_tumor_KRT5 == "KRT5+" & sce$GMM_tumor_KRT7 == "KRT7-", "KRT5+",
              ifelse(sce$GMM_tumor_KRT5 == "KRT5-" & sce$GMM_tumor_KRT7 == "KRT7+", "KRT7+","KRT5/7-")))

## Colors 
library(wesanderson)
metadata(sce)$colors$KRT57_score <- setNames(c("grey",wes_palette("Moonrise3")[1:3]), c("KRT5/7-", "KRT5/7+","KRT5+", "KRT7+"))

# Visualization 

## Number of cells per category 
n_cat <- colData(sce) %>% as.data.frame() %>% group_by(KRT5_7_score) %>% count()
n_cat <- n_cat %>% ungroup() %>% mutate(sum = sum(n)) %>% mutate(fra = (n/sum)*100)

ggplot(n_cat, aes(KRT5_7_score, n))+
  geom_bar(stat = "identity", aes(fill = KRT5_7_score))+
  theme_classic()+
  scale_fill_manual(values = metadata(sce)$colors$KRT57_score)

## Scatterplot
cur_dat <- t(assay(sce,"logcounts")) %>% as.matrix %>% as.data.frame %>% select("KRT5","KRT7")
cur_dat$KRT5_7_score <- sce$KRT5_7_score[match(rownames(cur_dat), rownames(colData(sce)))]
cur_dat$GMM_tumor_KRT7 <- sce$GMM_tumor_KRT7[match(rownames(cur_dat), rownames(colData(sce)))]
cur_dat$GMM_tumor_KRT5 <- sce$GMM_tumor_KRT5[match(rownames(cur_dat), rownames(colData(sce)))]


main <- ggplot(cur_dat, aes(x=KRT7, y=KRT5, color = KRT5_7_score)) +
  geom_point(alpha = 0.5)+
  theme_classic()+
  xlab("KRT7 logcounts")+
  ylab("KRT5 logcounts")+
  guides(color = "none")+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)

y_side <- ggplot(cur_dat, aes(x = KRT5, fill=GMM_tumor_KRT5)) + 
  geom_density(alpha=0.8) + 
  scale_fill_manual(values = c('#999999','#F4B5BD')) + 
  theme_classic()+
  theme(legend.position = "none", axis.title.y = element_blank())+
  coord_flip()

x_side <- ggplot(cur_dat, aes(x = KRT7, fill=GMM_tumor_KRT7)) + 
  geom_density(alpha=0.8) + 
  scale_fill_manual(values = c('#999999','#9C964A')) + 
  theme_classic()+
  theme(legend.position = "none", axis.title.x = element_blank())

blankPlot <- ggplot()+geom_blank(aes(1,1)) + 
  cowplot::theme_nothing()

library(gridExtra)
scatter_final <- grid.arrange(x_side, blankPlot, main, y_side, 
        ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))

## Dim Red
plotReducedDim(sce, dimred="UMAP", colour_by="KRT5_7_score")+
    scale_color_manual(values = metadata(sce)$colors$KRT57_score)
```

## Barplot overviews 

```{r}
# PID
dittoBarPlot(sce, var = "KRT5_7_score", group.by = "Patient_ID",scale="count")+
    scale_fill_manual(values = metadata(sce)$colors$KRT57_score)

dittoBarPlot(sce, var = "KRT5_7_score", group.by = "Patient_ID",scale="percent")+
    scale_fill_manual(values = metadata(sce)$colors$KRT57_score)

out_dat <- dittoBarPlot(sce, var = "KRT5_7_score", group.by = "Patient_ID",scale="percent", data.out = TRUE)[[2]]



# Cell types
dittoBarPlot(sce, var = "KRT5_7_score", group.by = "celltypes",scale="percent")+
    scale_fill_manual(values = metadata(sce)$colors$KRT57_score)

dittoBarPlot(sce, var = "KRT5_7_score", group.by = "celltypes",scale="count")+
  scale_fill_manual(values = metadata(sce)$colors$KRT57_score)
```

## Keratin expression

```{r}
keratins <- c("KRT5","KRT7","KRT15","KRT8","KRT18","KRT19", "KRT14","KRT17","ITGA6","EPCAM")

cluster_mean_sce <- aggregateAcrossCells(sce, ids = sce$KRT5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce)$Symbol %in% keratins)

scaled_mat <- t(scale(t(assay(cluster_mean_sce, "logcounts"))))

anno <- colData(sce) %>% as.data.frame() %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% count()
anno <- anno[match(anno$KRT5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(assay(cluster_mean_sce, "logcounts"), col = viridis(100),name = "Mean Expression")
Heatmap(t(scaled_mat), name = "Scaled mean expression")

# Add row annotations 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

## Stem marker expression 

```{r}
# Define stem markers of interest
stem <- c("SOX9","KIT","PROM1","YAP1","HDAC2","NOTCH1","CD44","ALDH1A3","BRCA1","BRCA2", "TGFB2", "ANXA8","MUC1")#"NT5E","TNF","NFKB1","EZH2"

cluster_mean_sce <- aggregateAcrossCells(sce, ids = sce$KRT5_7_score,
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce)$Symbol %in% stem)

scaled_mat <- t(scale(t(assay(cluster_mean_sce, "logcounts"))))

anno <- colData(sce) %>% as.data.frame() %>% select(KRT5_7_score) %>% group_by(KRT5_7_score) %>% count()
anno <- anno[match(anno$KRT5_7_score, rownames(t(scaled_mat))),]

## Print heatmap 
Heatmap(assay(cluster_mean_sce, "logcounts"), col = viridis(100),name = "Mean Expression")
Heatmap(scaled_mat, name = "Scaled mean expression")

# Add row annotations 
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
```

```{r}
# UMAP with stem/progenitor markers
all_plots_UMAP <- lapply(stem,
                    function(x){
                      p <- plotReducedDim(sce, dimred = "UMAP", colour_by = x, by_exprs_values = "logcounts", point_size = 0.3)
                      return(p)                    
                    })

library(cowplot)
all_plots_UMAP_exprs <- plot_grid(plotlist = all_plots_UMAP)
all_plots_UMAP_exprs
```

## Li et al signatures

A: Alveolar subtypes 

```{r}
library(readxl)
AV_sig <- read_excel("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/03_data/Lietal_AV_BL_Signatures_reduced.xlsx",sheet = 1)

colnames(AV_sig) <- c("pan_AV", "BL_enriched","AP_enriched")

# Extract unique genes that were up- or down-regulated in each signature 
panAV_sig_up <- AV_sig$pan_AV
panAV_sig_up <- panAV_sig_up[!is.na(panAV_sig_up)]

BL_sig_up <- AV_sig$BL_enriched
BL_sig_up <- BL_sig_up[!is.na(BL_sig_up)]

AP_sig_up <- AV_sig$AP_enriched
AP_sig_up <- AP_sig_up[!is.na(AP_sig_up)]
```

```{r}
## 1. pan AV signature per PID group 
panAV_sig_up_rel <- panAV_sig_up[panAV_sig_up %in% rownames(assay(sce))]

stem_mean_sce <- aggregateAcrossCells(sce, ids = DataFrame(sce$KRT5_7_score,sce$Patient_ID), #Aggregate for score AND per line 
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce)$Symbol %in% panAV_sig_up_rel)

test <- as.data.frame(scale(t(assay(stem_mean_sce, "logcounts")), center = TRUE))

plot_df <- data.frame(signature_score = rowSums(test), cat = stem_mean_sce$sce.KRT5_7_score, PID = stem_mean_sce$sce.Patient_ID)

#Boxplot 
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Pan-Alveolar signature (Li et al.)")+
  stat_compare_means()

# Heatmap 
test$cat <- stem_mean_sce$sce.KRT5_7_score

test_out <- test %>% pivot_longer(cols = 1:41, names_to = "genes", values_to = "exprs") %>% group_by(cat,genes) %>% summarize(sum = sum(exprs))

test_plot <- test_out %>% pivot_wider(names_from = genes, values_from = sum) %>% column_to_rownames("cat")

Heatmap(test_plot)
```

```{r}
## 2. BL signature per PID group 
BL_sig_up_rel <- BL_sig_up[BL_sig_up %in% rownames(assay(sce))]

stem_mean_sce <- aggregateAcrossCells(sce, ids = DataFrame(sce$KRT5_7_score,sce$Patient_ID), #Aggregate for score AND per PID
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce)$Symbol %in% BL_sig_up_rel)

test <- as.data.frame(scale(t(assay(stem_mean_sce, "logcounts")), center = TRUE))

plot_df <- data.frame(signature_score = rowSums(test), cat = stem_mean_sce$sce.KRT5_7_score, PID = stem_mean_sce$sce.Patient_ID)

#Boxplot 
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basal luminal signature (Li et al.)")+
  stat_compare_means()

# Heatmap 
test$cat <- stem_mean_sce$sce.KRT5_7_score

test_out <- test %>% pivot_longer(cols = 1:41, names_to = "genes", values_to = "exprs") %>% group_by(cat,genes) %>% summarize(sum = sum(exprs))

test_plot <- test_out %>% pivot_wider(names_from = genes, values_from = sum) %>% column_to_rownames("cat")

Heatmap(test_plot)
```

## Lim et al signatures

```{r}
library(readxl)
lum_progenitor_sig <- read_excel("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/03_data/LuminalProgenitor_Signature_Limetal_NatureMedicine_2009.xls")
mature_lum_sig <- read_excel("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/03_data/MatureLuminalSignature_Limetal_NatureMedicine_2009.xls")
basal_sig <- read_excel("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/03_data/Basal_Signature_Limetal_NatureMedicine_2009.xls")

# Extract unique genes that were up- or down-regulated in each signature 
lum_progenitor_sig_up <- lum_progenitor_sig %>% filter(`Average log fold-change` > 1) %>% pull(Symbol) %>% unique()
lum_progenitor_sig_up <- lum_progenitor_sig_up[!is.na(lum_progenitor_sig_up)]
lum_progenitor_sig_down <- lum_progenitor_sig %>% filter(`Average log fold-change` < -1) %>% pull(Symbol) %>% unique()
lum_progenitor_sig_down <- lum_progenitor_sig_down[!is.na(lum_progenitor_sig_down)]

mature_lum_sig_up <- mature_lum_sig %>% filter(`Average log fold-change` > 1) %>% pull(Symbol) %>% unique()
mature_lum_sig_up <- mature_lum_sig_up[!is.na(mature_lum_sig_up)]
mature_lum_sig_down <- mature_lum_sig %>% filter(`Average log fold-change` < -1) %>% pull(Symbol) %>% unique()
mature_lum_sig_down <- mature_lum_sig_down[!is.na(mature_lum_sig_down)]

basal_sig_up <- basal_sig %>% filter(`Average log fold-change` > 1) %>% pull(Symbol) %>% unique()
basal_sig_up <- basal_sig_up[!is.na(basal_sig_up)]
basal_sig_down <- basal_sig %>% filter(`Average log fold-change` < -1) %>% pull(Symbol) %>% unique()
basal_sig_down <- basal_sig_down[!is.na(basal_sig_down)]
```

```{r}
## 1. Luminal progenitor signature per PID group 
lum_progenitor_sig_up_rel <- lum_progenitor_sig_up[lum_progenitor_sig_up %in% rownames(assay(sce))]

stem_mean_sce <- aggregateAcrossCells(sce, ids = DataFrame(sce$KRT5_7_score,sce$Patient_ID), #Aggregate for score AND per PID
                                 statistics = "mean",
                                 use.assay.type = "logcounts",
                                 subset.row = rowData(sce)$Symbol %in% lum_progenitor_sig_up_rel)

test <- as.data.frame(scale(t(assay(stem_mean_sce, "logcounts")), center = TRUE))

plot_df <- data.frame(signature_score = rowSums(test,na.rm = TRUE), cat = stem_mean_sce$sce.KRT5_7_score, PID = stem_mean_sce$sce.Patient_ID)

#Boxplot 
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Luminal progenitor signature (Lim et al.)")+
  stat_compare_means()

# Heatmap 
test$cat <- stem_mean_sce$sce.KRT5_7_score

test_out <- test %>% pivot_longer(cols = 1:41, names_to = "genes", values_to = "exprs") %>% group_by(cat,genes) %>% summarize(sum = sum(exprs))

test_plot <- test_out %>% pivot_wider(names_from = genes, values_from = sum) %>% column_to_rownames("cat")

Heatmap(test_plot)
```

## Save plots

```{r}
## Save plots as pdf

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_Heatmap_Keratins.pdf",height = 4, width = 7, onefile = FALSE)
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_UMAP_Keratins.pdf",height = 10, width = 10, onefile = FALSE)
all_plots_UMAP_keratins
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_Scatter_Density.pdf",height = 5, width = 6, onefile = FALSE)
scatter_final <- grid.arrange(x_side, blankPlot, main, y_side, 
        ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_PID_Barplot.pdf",height = 4, width = 7, onefile = FALSE)
dittoBarPlot(sce, var = "KRT5_7_score", group.by = "Patient_ID",scale="percent")+
    scale_fill_manual(values = metadata(sce)$colors$KRT57_score)
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_Heatmap_Stem.pdf",height = 4, width = 9, onefile = FALSE)
Heatmap(t(scaled_mat), name = "Scaled mean expression")+
  rowAnnotation(n = anno_barplot(anno$n, gp = gpar(fill = "#440154FF")))+
  rowAnnotation(anno = anno_text(anno$KRT5_7_score))
dev.off()


pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_PanAV_Boxplot.pdf",height = 5, width = 5, onefile = FALSE)
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Pan-Alveolar signature (Li et al.)")+
  stat_compare_means()
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_BLSignature_Boxplot.pdf",height = 5, width = 5, onefile = FALSE)
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basal luminal signature (Li et al.)")+
  stat_compare_means()
dev.off()


pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_BLSignature_Boxplot.pdf",height = 5, width = 5, onefile = FALSE)
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Basal luminal signature (Li et al.)")+
  stat_compare_means()
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_BLSignature_Heaptmap.pdf",height = 4, width = 9, onefile = FALSE)
Heatmap(test_plot, name = "Expression")
dev.off()

pdf("/mnt/central_nas/tnbc_volume/TNBC/data_analysis/01_figures/scRNA_organoid/Organoid_scRNA_CK57score_LumProgenitorLIM_Boxplot.pdf",height = 5, width = 5, onefile = FALSE)
ggplot(plot_df, aes(x = cat, y = signature_score))+
  geom_boxplot(outlier.color = NA)+
  geom_jitter(aes(color = cat), size = 3, position=position_jitter(w=0.1,h=0.1))+
  scale_color_manual(values = metadata(sce)$colors$KRT57_score)+
  theme_classic()+
  ylab("Luminal progenitor signature (Lim et al.)")+
  stat_compare_means()
dev.off()

```

