---
title: "SCRNAseq_tumor_analysis"
author: "Lasse Meyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Software requirements

```{r lib, message=FALSE,warning=FALSE}
#Data containers
library(SpatialExperiment)
library(SingleCellExperiment)

#Data processing
library(scuttle)
library(scater)
library(scran)
library(imcRtools)

#Data visualization
library(cytomapper)
library(dittoSeq)
library(pheatmap)
library(cowplot)
library(ComplexHeatmap)
library(circlize)

#Utilities
library(tidyverse)
library(openxlsx)
library(stringr)
library(patchwork)
library(parallel)
library(BiocParallel)
library(BiocNeighbors)
library(BiocSingular)
library(tiff)
library(ggrepel)
library(EBImage)
library(viridis)
library(mclust)
library(Rphenograph)
library(igraph)
library(RColorBrewer)
library(foreach)
library(clValid)
library(bluster)
library(psych)
library(corrplot)
library(psych)

#Batch correction
library(batchelor)
```

# scRNAseq analysis - Tumor cell analysis

Data from GSE161529 - 8 TNBC patients (4 BRCA-/+) - Pal et al. (2021, EMBO Journal)


## 1. Load sce and subset to tumor cells

Subset sce to focus on tumor cells

```{r}
sce <- readRDS("/mnt/tnbc_volume/GSE161529/data_analysis/sce_scRNA_anacat.rds")

sce <- sce[,sce$analysis_cat == "Epithelial"] 
sce
```

## 2. Feature selection 

```{r}
var_sce <- modelGeneVar(sce)
hvg_sce <- getTopHVGs(var_sce, prop=0.1)
hvg <- str(hvg_sce)

# Check whether cytokeratin 5/7 are part of hvgs
summary(hvg_sce %in% c("KRT5","KRT7"))

# Add to sce
rowSubset(sce, "HVG_tumor") <- getTopHVGs(var_sce, prop=0.1)
colnames(rowData(sce))
```

## 3. Dimensionality reduction

```{r}
# Visualize 
sce <- runTSNE(sce, subset_row = rowData(sce)$HVG_tumor, dimred = "fastMNN", name = "TSNE_MNN_tumor",BPPARAM = MulticoreParam())
plotReducedDim(sce, dimred="TSNE_MNN_tumor", colour_by="PID")
```

## 4. Graph-based clustering

```{r}
graph_clust <- clusterCells(x = sce, use.dimred = "fastMNN",
                      BLUSPARAM = NNGraphParam(k=30,
                                               cluster.fun ="louvain",
                                               type="jaccard",
                                               BPPARAM=MulticoreParam(workers = 20)))

sce$tumor_cluster_30 <- graph_clust                   

graph_clust <- clusterCells(x = sce, use.dimred = "fastMNN",
                      BLUSPARAM = NNGraphParam(k=50,
                                               cluster.fun ="louvain",
                                               type="jaccard",
                                               BPPARAM=MulticoreParam(workers = 20)))
                      
sce$tumor_cluster_50 <- graph_clust

graph_clust <- clusterCells(x = sce, use.dimred = "fastMNN",
                      BLUSPARAM = NNGraphParam(k=70,
                                               cluster.fun ="louvain",
                                               type="jaccard",
                                               BPPARAM=MulticoreParam(workers = 20)))
                      
sce$tumor_cluster_70 <- graph_clust

graph_clust <- clusterCells(x = sce, use.dimred = "fastMNN",
                      BLUSPARAM = NNGraphParam(k=90,
                                               cluster.fun ="louvain",
                                               type="jaccard",
                                               BPPARAM=MulticoreParam(workers = 20)))
                      
sce$tumor_cluster_90 <- graph_clust

# Define cluster colors
cluster_col <- setNames(colorRampPalette(brewer.pal(9, "Paired"))(length(unique(sce$tumor_cluster_90))),unique(sce$tumor_cluster_90))

plotReducedDim(sce, dimred="TSNE_MNN_tumor", colour_by="tumor_cluster_70", text_by = "tumor_cluster_70")+
  scale_color_manual(values = cluster_col)

plotReducedDim(sce, dimred="TSNE_MNN_tumor", colour_by="tumor_cluster_90", text_by = "tumor_cluster_90")+
  scale_color_manual(values = cluster_col)
```
### Cluster stability testing

```{r}
#Pairwise rand index 
#Agreement between two clustering approaches - ARI > 0.5 = "good" similarity
pairwiseRand(sce$tumor_cluster_30,sce$tumor_cluster_50, mode = "index")
pairwiseRand(sce$tumor_cluster_50,sce$tumor_cluster_70, mode = "index")
pairwiseRand(sce$tumor_cluster_70,sce$tumor_cluster_90, mode = "index")

#Over different resolution parameters - Silhouette width [-1,1,max], Purity[0,1,max], Root-mean-squared difference [min]
clusters <- colnames(colData(sce))[str_detect(colnames(colData(sce)),"tumor_cluster_[:digit:]")]
df <- foreach(i = seq_along(clusters),.combine = rbind) %do% {
num_clus <- length(unique(colData(sce)[,clusters[i]]))
sil <- approxSilhouette(reducedDim(sce, "fastMNN"), clusters=colData(sce)[,clusters[i]])
rmsd <- clusterRMSD(reducedDim(sce, "fastMNN"), clusters=colData(sce)[,clusters[i]])
data.frame(num_clus = num_clus,
           k = as.numeric(str_split(clusters[i],"_",simplify = TRUE)[,3]), 
           sil = mean(sil$width), 
#           purity = mean(purity$purity),
           rmsd = sum(rmsd))
}


p1 <- ggplot(df, aes(x=k, y=num_clus))+
  geom_point(aes(k, num_clus, col = num_clus))+
  geom_line(aes(k, num_clus,col=num_clus))+
  theme_classic()+
  scale_color_continuous(type = "viridis")

p2 <- ggplot(df, aes(x=k, y=rmsd))+
  geom_point(aes(k, rmsd, col = rmsd))+
  geom_line(aes(k, rmsd,col=rmsd))+
  theme_classic()+
  scale_color_continuous(type = "viridis")

p3 <- ggplot(df, aes(x=k, y=sil))+
  geom_point(aes(k, sil, col = sil))+
  geom_line(aes(k, sil,col=sil))+
  theme_classic()+
  scale_color_continuous(type = "viridis")
  
p1+p2+p3 
# k=90 for downstream analysis
```

## CK5-7 signature

```{r}
## add CK5 and CK7 GMM
# 1. CK5
GMM_CK5 <- Mclust(assay(sce, "logcounts")["KRT5",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK5$classification == 2, 
                                        "KRT5+",
                                        "KRT5-"), 
                     KRT5_exprs = assay(sce, "logcounts")["KRT5",],
                     uncertainty = GMM_CK5$uncertainty)

#Visualize GMM
ggplot(GMM_df, aes(x = KRT5_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_KRT5 <- GMM_df$class_epi

# 2. CK7
GMM_CK7 <- Mclust(assay(sce, "logcounts")["KRT7",], G = 2)

GMM_df <- data.frame(class_epi = ifelse(GMM_CK7$classification == 2, 
                                        "KRT7+",
                                        "KRT7-"), 
                     KRT7_exprs = assay(sce, "logcounts")["KRT7",],
                     uncertainty = GMM_CK7$uncertainty)

#Visualize GMM
ggplot(GMM_df, aes(x = KRT7_exprs, fill = class_epi))+
  geom_density()+
  theme_classic(base_size = 15)+
  theme(axis.title.x = element_blank())+
  scale_fill_brewer(palette = "Set1")
  
#Add GMM epi class to SCE
sce$GMM_tumor_KRT7 <- GMM_df$class_epi

## Combine KRT5/7 GMM scores 
sce$KRT5_7_score <- ifelse(sce$GMM_tumor_KRT5 == "KRT5+" & sce$GMM_tumor_KRT7 == "KRT7+", "KRT5/7+", 
       ifelse(sce$GMM_tumor_KRT5 == "KRT5+" & sce$GMM_tumor_KRT7 == "KRT7-", "KRT5+",
              ifelse(sce$GMM_tumor_KRT5 == "KRT5-" & sce$GMM_tumor_KRT7 == "KRT7+", "KRT7+","KRT5/7-")))

metadata(sce)$colors$KRT5_7_score <- setNames(colorRampPalette(brewer.pal(4,"Set1"))(length(unique(sce$KRT5_7_score))),unique(sce$KRT5_7_score))

# dittoScatterPlot(
#     object = sce,
#     x.var = "KRT7", y.var = "KRT5",
#     color.var = "KRT5_7_score")

cur_dat <- t(assay(sce,"logcounts")) %>% as.matrix %>% as.data.frame %>% select("KRT5","KRT7")
cur_dat$KRT5_7_score <- sce$KRT5_7_score[match(rownames(cur_dat), sce$cell_id)]

ggplot(cur_dat, aes(x=KRT7, y=KRT5, color = KRT5_7_score)) +
  geom_point(alpha = 0.5)+
  theme_classic()+
  xlab("KRT7 logcounts")+
  ylab("KRT5 logcounts")+
  scale_color_manual(values = metadata(sce)$colors$KRT5_7_score)

plotReducedDim(sce, dimred = "TSNE_MNN_tumor", 
               colour_by = "KRT5", 
               by_exprs_values = "logcounts")

plotReducedDim(sce, dimred = "TSNE_MNN_tumor", 
               colour_by = "KRT7", 
               by_exprs_values = "logcounts")

plotReducedDim(sce, dimred = "TSNE_MNN_tumor", 
               colour_by = "KRT8", 
               by_exprs_values = "logcounts")

plotReducedDim(sce, dimred = "TSNE_MNN_tumor", 
               colour_by = "KRT18", 
               by_exprs_values = "logcounts")

plotReducedDim(sce, dimred="TSNE_MNN_tumor", colour_by="KRT5_7_score")+
  scale_color_manual(values = metadata(sce)$colors$KRT5_7_score)

plotExpression(sce, features=c("KRT5", "KRT7", "KRT8", "KRT14","KRT18"),
    x="KRT5_7_score", colour_by="KRT5_7_score")+
  theme_classic()+
  scale_color_manual(values = metadata(sce)$colors$KRT5_7_score)
```

```{r}
library(tidyverse)
for_plot <- colData(sce) %>% as.data.frame %>%
    group_by(tumor_cluster_90, KRT5_7_score) %>%
    summarize(count = n()) %>%
    mutate(freq = count / sum(count)) %>%
    pivot_wider(id_cols = KRT5_7_score, names_from = tumor_cluster_90, 
                values_from = freq, values_fill = 0) %>%
    ungroup() %>%
    column_to_rownames("KRT5_7_score")

Heatmap(for_plot,
        col = viridis(100),
        show_row_names = TRUE)
```

```{r}
dittoBarPlot(sce, var = "KRT5_7_score", group.by = "PID")+
  scale_fill_manual(values = metadata(sce)$colors$KRT5_7_score)

dittoBarPlot(sce, var = "KRT5_7_score", group.by = "PID", scale = "count")+
  scale_fill_manual(values = metadata(sce)$colors$KRT5_7_score)

dittoBarPlot(sce, var = "PID", group.by = "KRT5_7_score")
dittoBarPlot(sce, var = "PID", group.by = "KRT5_7_score", scale = "count")
```
Save sce

```{r}
saveRDS(sce, "/mnt/tnbc_volume/GSE161529/data_analysis/sce_scRNA_tumor.rds")
```
